---
# tasks file for docker
- name: Docker GPG key & Sources list setup
  block:
    - name: Create directory to store Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Create sources list for Docker
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

- name: Docker GPG key & Repository setup # armored keys should use .asc extension, binary should use .gpg
  block:
    - name: Download Docker’s GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a=r

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

- name: Install Docker Engine, CLI, Containerd, and plugins
  block:
    - name: Upddate apt packages
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ dockerengine_packages }}"
    - name: Assign vagrant to Docker group
      ansible.builtin.shell:
        cmd: "sudo usermod -aG docker {{ ansible_user }}"

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
