---
# tasks file for common
- name: Install Docker Engine, CLI, Containerd, and plugins
  block:
    - name: Upddate apt packages
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_packages }}"
